# Generated by Django 5.1.5 on 2025-03-24 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_recipe_created_on_alter_recipe_updated_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('description', models.CharField(max_length=255)),
                ('illustration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Illustration', to='ledger.recipe')),
            ],
        ),
    ]
