# Generated by Django 5.1.6 on 2025-03-25 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_alter_recipeimage_illustration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeimage',
            name='illustration',
        ),
        migrations.AddField(
            model_name='recipeimage',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe', to='ledger.recipe'),
        ),
    ]
