# Generated by Django 5.1.6 on 2025-03-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_remove_recipeimage_illustration_recipeimage_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
