# Generated by Django 5.1.6 on 2025-03-25 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0001_initial'),
        ('ledger', '0007_alter_recipeimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='Author',
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='UserAccounts.profile'),
        ),
    ]
